version: '3'

services:  
    web:
        build: .
        ports:
        - "5000:5000"
        volumes:
        - .:/code

    database:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "33602:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=testdatabase
            - MYSQL_USER=root
            - MYSQL_PASSWORD=secret